version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        # Update 'VARIANT' to pick an LTS version of Node.js: 16, 14, 12.
        # Append -bullseye or -buster to pin to an OS version.
        # Use -bullseye variants on local arm64/Apple Silicon.
        VARIANT: 18

    volumes:
      - ..:/workspace:cached

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
    network_mode: service:db

    # Uncomment the next line to use a non-root user for all processes.
    # user: node

    # Use "forwardPorts" in **devcontainer.json** to forward an app port locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)

  db:
    image: mongo:latest
    restart: unless-stopped
    volumes:
      - mongodb-data:/data/db

    # Uncomment to change startup options
    environment:
      MONGO_INITDB_ROOT_USERNAME: E89F3
      MONGO_INITDB_ROOT_PASSWORD: 7S3ZRlemktbNFj3qkxoT2IC8fkeOwz48
      MONGO_INITDB_DATABASE: clhr9zYgGM

    # Add "forwardPorts": ["27017"] to **devcontainer.json** to forward MongoDB locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)
    healthcheck:
      test: >
        if mongo --quiet db/test --eval 'quit(db.runCommand({ ping: 1 }).ok ? 0 : 2)'; then
          exit 0
        fi
      interval: 15s
      timeout: 20s
      retries: 3
      start_period: 15s
  
  mail:
    image: maildev/maildev:latest
    restart: unless-stopped
    network_mode: service:db
    environment:
      - MAILDEV_INCOMING_USER=59CA4
      - MAILDEV_INCOMING_PASS=vSbPPkYJoi38tV8n7pXZT1truz8hjzp0
    healthcheck:
      test: wget -qO- http://localhost:1080/healthz
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 40s
  
  tracing:
    image: jaegertracing/all-in-one:latest
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    restart: unless-stopped
    network_mode: service:db

  storage:
    image: minio/minio:latest
    environment:
      - MINIO_ROOT_USER=1898pCxJjE
      - MINIO_ROOT_PASSWORD=Qt4sNRHXlBJM34ENVN9mbCHrF4Tkmk3S
    volumes:
      - minio-data:/data
    command: server --console-address ":9001" /data
    network_mode: service:db
    restart: unless-stopped
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:9000/minio/health/live']
      interval: 30s
      timeout: 20s
      retries: 3

volumes:
  mongodb-data:
  minio-data: